### ISSUE TITLE
How to style the DockAreaTabBar

### ISSUE THREAD

**Issue by Yoonwoo** [githubuser0xFFFF/Qt-Advanced-Docking-System#10]
Im trying to style the grey tab area and I know it works if I directly use set stylesheet on it where its created, but that makes it style after the default.css and layers over it. 

I try some styles:
`
ads--CDockAreaTabBar
{
    background: #cccccc;
}
CDockAreaTabBar
{
    background: #cccccc;
}
`

Can you please tell me how to style it?

PS: This library is incredible, I cant believe its this good.

**Comment by githubuser0xFFFF** [comment]
You can try this:

```css
ads--CDockAreaTabBar #tabsContainerWidget
{
	background: rgb(81, 81, 81);
}
```
