### ISSUE TITLE
Modifying ContentsMargins?

### ISSUE THREAD

**Issue by AV9** [githubuser0xFFFF/Qt-Advanced-Docking-System#161]
Hello githubuser0xFFFF!

First of all I would like to thank you for your great job! The reason why i'm writing to you is because I couldn't find the way to modify the spacing between the Docks. Tried also disabling the standard stylesheet by:

`m_DockManager->setStyleSheet("");`

and then setting the padding inside a *.css file, but so far no success...

![image](https://user-images.githubusercontent.com/2632460/81415349-9f081000-9148-11ea-8489-b5520f3bd3bf.png)

Any suggestion?
Thanks in advance!

**Comment by AV9** [comment]
Ok, fixed. This was the solution:

ads--CDockContainerWidget QSplitter::handle
{
    padding: -2px;
}

Thanks!

**Comment by AV9** [comment]
Ok, I reopen again the issue for a similar thing, Is it possible to make the separation lines mentioned above to one line like the Qt Creator does?

Setting the padding to negative like I posted before reaches the target but then the mouse icon for changing the size doesn't appear anymore and therefore the dock size becomes fixed.

Any idea about that?

**Comment by githubuser0xFFFF** [comment]
According to the [Qt documentation](https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsplitter) it should be possible with the following code:

```css
QSplitter::handle:horizontal {
    width: 2px;
}

QSplitter::handle:vertical {
    height: 2px;
}
```

But this does not work for me. But the following code works for me and changes horizontal as well as vertical splitters:

```css
ads--CDockSplitter::handle
{
    background: palette(dark);
    height: 1px;
}
```

Pleae check, if this works for you
