### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by felipefrr** [githubuser0xFFFF/Qt-Advanced-Docking-System#205]
I need help to change the font inside the tab of the CDockWidget, I want to change the title's font, it seems that setting a style-sheet doesn't work.
I'm trying change the way of detachment of the widgets happens, I want to make all the widgets detach together, the same way it happens with tabs of CDockWidget and they float inside same window, and block the individual floating. Is that possible?
Someone has any tips?
 

PS: It's my first time starting an issue and using git for a problem in work. I'm nervous.

**Comment by githubuser0xFFFF** [comment]
Hi,

you can change the font of the tab this way:

```css
ads--CDockWidgetTab QLabel {
	color: palette(dark);
	font: bold italic large "Times New Roman";
}

I just tested it in the demo application and it works.

What you mentioned in your second request is not possible. You can dock and undock single dock widgets or dock areas with a group of tabbed dock widgets.
```
