### ISSUE TITLE
Calling Update() / Repaint() Non-Focused Window

### ISSUE THREAD

**Issue by Snolandia** [githubuser0xFFFF/Qt-Advanced-Docking-System#715]
After changing something from a separate window, such as color/style, calling Repaint() or Update() on either the mainwindow, dockManager, or tab itself does not trigger a repaint or update of the widget and an update/repaint is not processed until I click back to the mainwindow(not necessarily on the tab). Other components of the mainwindow do get updated as expected, it is solely the ADS widgets that dont. 

Ive spent some time debugging and going through the ADS code but cant seem to find where/what the trigger is for this, and/or what is blocking the repaint event. 

Any help would be much appreciated. 

As a note, I believe issue #695 is the same issue, though the thread didnt help at all as this has nothing to do with style-sheets as far as I can tell as Im using palettes for colors.

**Comment by githubuser0xFFFF** [comment]
What did you change?

**Comment by Snolandia** [comment]
The palettes being used for all the components.

**Comment by jeandet** [comment]
Hello,

I might have the same issue with a docked widget that holds a property **selected** with the following qss:
```CSS
SciQLopPlotInterface{
    margin: 0px;
    padding: 0px;
}

SciQLopPlotInterface[selected=false] {
    border: 0px;
}

SciQLopPlotInterface[selected=true] {
    border: 3px solid black;
    border-style: dashed;
}
```
It used to work with QTADS, now it only update the selected widget when either reloading the style-sheet or switching between tabs. In the following screenshot, I only get that dashed line after switching between `Panel1` and `Panel0` and then back to `Panel1`. 

![Image](https://github.com/user-attachments/assets/1f100fd3-02a7-4265-b1c0-a94497219690)

I'm using Qt 6.8.2, I've only tested on Linux using xcb backend with XWayland on Gnome desktop so far.
